import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "Next Tutorial | Kewa Code",
    template: "%s | Kewa",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header style={{ background: "#33303E", color: "#f1f1f1" }}>
          Cabeçalho da aplicação
        </header>
        {children}
        <footer style={{ background: "#33303E", color: "#f1f1f1" }}>
          Rodapé da aplicação
        </footer>
      </body>
    </html>
  );
}
